<?php

/**
 * AnuncianteFotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncianteFotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncianteFotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncianteFoto');
    }
}