<?php

/**
 * AnuncianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Anunciante');
    }
}