<?php

/**
 * AnuncianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Anunciante');
    }
    

    public function getWhereQuery($wheres)
    {
    	$q = $this->createQuery('a')
    	->where('1 = 1');
    
    	foreach($wheres as $where){
    		$q->andWhere($where);
    	}
    	 
    	return $q;
    }
}