<?php

/**
 * GaleriaFotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaFotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriaFotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GaleriaFoto');
    }
}