<?php

/**
 * GaleriaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object GaleriaTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Galeria');
	}
	public function obtenerUltimo(){
		$q = $this->createQuery('g')
		->where('1 = 1')
		->orderBy('g.created_at DESC');
		return $q->fetchOne();
	}

	public function getAllNewest($limit = null){
		$q = $this->createQuery('g')
		->where('1 = 1')
		->orderBy('g.created_at DESC');
		if($limit)
			$q->limit($limit);
		return $q->execute();
	}
}