<?php

/**
 * NovedadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovedadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovedadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Novedad');
    }
    
    public function getAllSorteos(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Sorteo");
    	return $q->execute();
    }
    
    public function getAllRecetas(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Receta");
    	return $q->execute();
    }
    public function getAllPulguitas(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Pulguita");
    	return $q->execute();
    }
}