<?php

/**
 * NovedadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovedadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovedadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Novedad');
    }
    
    public function getAllSorteos(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Sorteo");
    	return $q->execute();
    }
    
    public function getAllRecetas(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Receta");
    	return $q->execute();
    }
    public function getAllPulguitas(){
    	$q = $this->createQuery('n')
    	->where('n.tipo= ?', "Pulguita");
    	return $q->execute();
    }
    
    public function getAllNewest($limit = null){
    	$q = $this->createQuery('s')
    	->where('1= 1')
    	->orderBy('s.created_at DESC');
    	if($limit)
    		$q->limit($limit);
    	return $q->execute();
    }
    
    public function obtenerUltimo(){
    	$q = $this->createQuery('r')
    	->where('1= 1')
    	->orderBy('r.created_at DESC');
    	return $q->fetchOne();
    }
}