<?php

/**
 * PublicidadFotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicidadFotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicidadFotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicidadFoto');
    }
}