<?php

/**
 * PulguitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PulguitaTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PulguitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pulguita');
    }
    
    public function getAllNewest(){
    	$q = $this->createQuery('p')
    	->where('1= 1')
    	->orderBy('p.created_at DESC');
    	return $q->execute();
    }
}