<?php

/**
 * PulguitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PulguitaTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PulguitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pulguita');
    }
    
}