<?php

/**
 * RecetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecetaTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Receta');
    }
    
    public function getAllNewest(){
    	$q = $this->createQuery('r')
    	->where('1= 1')
    	->orderBy('r.created_at DESC');
    	return $q->execute();
    }
}