<?php

/**
 * RecetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecetaTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Receta');
    }
}