<?php

/**
 * RevistaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RevistaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RevistaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Revista');
    }
    
    public function obtenerUltimo(){
    	$q = $this->createQuery('r')
    	->where('1= 1')
    	->orderBy('r.created_at DESC');
    	return $q->fetchOne();
    }
}