<?php

/**
 * SorteoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SorteoTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SorteoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sorteo');
    }
    
}