<?php

/**
 * SorteoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SorteoTable extends NovedadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SorteoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sorteo');
    }
    
    public function getAllNewest(){
    	$q = $this->createQuery('s')
    	->where('1= 1')
    	->orderBy('s.created_at DESC');
    	return $q->execute();
    }
}