<?php

/**
 * SubCategoriaAnuncianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaAnuncianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubCategoriaAnuncianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubCategoriaAnunciante');
    }
}