<?php

/**
 * SubCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubCategoria');
    }
    
    public function getByCategoria($categoriaId) {
    	$q = $this->createQuery('sc')
    	->where('sc.categoria_id = ?', $categoriaId);
    	return $q->execute();
    }
    public function getByCodigoCategoria($codigo) {
    	$q = $this->createQuery('sc')
    	->innerJoin('sc.Categoria c')
    	->where('c.codigo LIKE ?', $codigo);
    	return $q->execute();
    }
}