<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/16 00:57:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pulgas',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
