<?php

/**
 * BaseAnunciante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $direccion
 * @property string $localidad
 * @property string $telefono
 * @property string $email
 * @property string $web
 * @property string $facebook
 * @property string $anuncio
 * @property Doctrine_Collection $SubCategorias
 * @property Doctrine_Collection $SubCategoriaAnunciante
 * @property Doctrine_Collection $Fotos
 * 
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method string              getDireccion()              Returns the current record's "direccion" value
 * @method string              getLocalidad()              Returns the current record's "localidad" value
 * @method string              getTelefono()               Returns the current record's "telefono" value
 * @method string              getEmail()                  Returns the current record's "email" value
 * @method string              getWeb()                    Returns the current record's "web" value
 * @method string              getFacebook()               Returns the current record's "facebook" value
 * @method string              getAnuncio()                Returns the current record's "anuncio" value
 * @method Doctrine_Collection getSubCategorias()          Returns the current record's "SubCategorias" collection
 * @method Doctrine_Collection getSubCategoriaAnunciante() Returns the current record's "SubCategoriaAnunciante" collection
 * @method Doctrine_Collection getFotos()                  Returns the current record's "Fotos" collection
 * @method Anunciante          setNombre()                 Sets the current record's "nombre" value
 * @method Anunciante          setDireccion()              Sets the current record's "direccion" value
 * @method Anunciante          setLocalidad()              Sets the current record's "localidad" value
 * @method Anunciante          setTelefono()               Sets the current record's "telefono" value
 * @method Anunciante          setEmail()                  Sets the current record's "email" value
 * @method Anunciante          setWeb()                    Sets the current record's "web" value
 * @method Anunciante          setFacebook()               Sets the current record's "facebook" value
 * @method Anunciante          setAnuncio()                Sets the current record's "anuncio" value
 * @method Anunciante          setSubCategorias()          Sets the current record's "SubCategorias" collection
 * @method Anunciante          setSubCategoriaAnunciante() Sets the current record's "SubCategoriaAnunciante" collection
 * @method Anunciante          setFotos()                  Sets the current record's "Fotos" collection
 * 
 * @package    pulgas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnunciante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anunciante');
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('direccion', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('localidad', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('web', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('facebook', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('anuncio', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SubCategoria as SubCategorias', array(
             'refClass' => 'SubCategoriaAnunciante',
             'local' => 'anunciante_id',
             'foreign' => 'sub_categoria_id'));

        $this->hasMany('SubCategoriaAnunciante', array(
             'local' => 'id',
             'foreign' => 'anunciante_id'));

        $this->hasMany('AnuncianteFoto as Fotos', array(
             'local' => 'id',
             'foreign' => 'anunciante_id'));
    }
}