<?php

/**
 * BaseSubCategoriaAnunciante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sub_categoria_id
 * @property integer $anunciante_id
 * @property Anunciante $Anunciante
 * @property SubCategoria $SubCategoria
 * 
 * @method integer                getSubCategoriaId()   Returns the current record's "sub_categoria_id" value
 * @method integer                getAnuncianteId()     Returns the current record's "anunciante_id" value
 * @method Anunciante             getAnunciante()       Returns the current record's "Anunciante" value
 * @method SubCategoria           getSubCategoria()     Returns the current record's "SubCategoria" value
 * @method SubCategoriaAnunciante setSubCategoriaId()   Sets the current record's "sub_categoria_id" value
 * @method SubCategoriaAnunciante setAnuncianteId()     Sets the current record's "anunciante_id" value
 * @method SubCategoriaAnunciante setAnunciante()       Sets the current record's "Anunciante" value
 * @method SubCategoriaAnunciante setSubCategoria()     Sets the current record's "SubCategoria" value
 * 
 * @package    pulgas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubCategoriaAnunciante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_categoria_anunciante');
        $this->hasColumn('sub_categoria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('anunciante_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anunciante', array(
             'local' => 'anunciante_id',
             'foreign' => 'id'));

        $this->hasOne('SubCategoria', array(
             'local' => 'sub_categoria_id',
             'foreign' => 'id'));
    }
}