<?php

/**
 * BaseSubCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $categoria_id
 * @property Categoria $Categoria
 * @property Doctrine_Collection $Anunciantes
 * @property Doctrine_Collection $SubCategoriaAnunciante
 * 
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method integer             getCategoriaId()            Returns the current record's "categoria_id" value
 * @method Categoria           getCategoria()              Returns the current record's "Categoria" value
 * @method Doctrine_Collection getAnunciantes()            Returns the current record's "Anunciantes" collection
 * @method Doctrine_Collection getSubCategoriaAnunciante() Returns the current record's "SubCategoriaAnunciante" collection
 * @method SubCategoria        setNombre()                 Sets the current record's "nombre" value
 * @method SubCategoria        setCategoriaId()            Sets the current record's "categoria_id" value
 * @method SubCategoria        setCategoria()              Sets the current record's "Categoria" value
 * @method SubCategoria        setAnunciantes()            Sets the current record's "Anunciantes" collection
 * @method SubCategoria        setSubCategoriaAnunciante() Sets the current record's "SubCategoriaAnunciante" collection
 * 
 * @package    pulgas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_categoria');
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Anunciante as Anunciantes', array(
             'refClass' => 'SubCategoriaAnunciante',
             'local' => 'sub_categoria_id',
             'foreign' => 'anunciante_id'));

        $this->hasMany('SubCategoriaAnunciante', array(
             'local' => 'id',
             'foreign' => 'sub_categoria_id'));
    }
}