<?php

/**
 * BaseAnuncianteFoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $anunciante_id
 * @property string $filename
 * @property string $caption
 * @property Anunciante $Anunciante
 * 
 * @method integer        getAnuncianteId()  Returns the current record's "anunciante_id" value
 * @method string         getFilename()      Returns the current record's "filename" value
 * @method string         getCaption()       Returns the current record's "caption" value
 * @method Anunciante     getAnunciante()    Returns the current record's "Anunciante" value
 * @method AnuncianteFoto setAnuncianteId()  Sets the current record's "anunciante_id" value
 * @method AnuncianteFoto setFilename()      Sets the current record's "filename" value
 * @method AnuncianteFoto setCaption()       Sets the current record's "caption" value
 * @method AnuncianteFoto setAnunciante()    Sets the current record's "Anunciante" value
 * 
 * @package    pulgas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnuncianteFoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anunciante_foto');
        $this->hasColumn('anunciante_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anunciante', array(
             'local' => 'anunciante_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}