# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

anunciante:
  url:   /anunciante
  param: { module: anunciante,action: index }
  
newSorteo:
  url:   /nuevoSorteo
  param: { module: novedad,action: newSorteo }

newPulguita:
  url:   /nuevaPulguita
  param: { module: novedad,action: newPulguita }

newReceta:  
  url:   /nuevaReceta
  param: { module: novedad,action: newReceta }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }



default:
  url:   /:module/:action/*
